### PR TITLE
Fix for newer OTP versions

### PR DESCRIPTION
**Pull request by Ninigi**
Erlang OTP 26 changed the default settings for ssl, breaking TLS for this package https://www.erlang.org/news/164#ssl

The cipher suite is an older change (OTP 21), so I am not sure why it is needed now, but was fine before, but it does not work for me without passing the ciphers to HTTPoison (down to hackney).

Tested against localhost and live server with

Elixir:
- 1.15.6-otp-25
- 1.17.2-otp-27

Erlang:
- 25.3.2.13
- 27.0.1

NOTE: some changes are caused by elixir formatter, because I have format on save activated in my editor.

### CODE REVIEW

**Comment by edouardmenayde** [comment]
Compiles without problem on our project @Ninigi ;)

**Comment by edouardmenayde** [comment]
Is there anything I can do to help get this merged ?

**Comment by Ninigi** [comment]
@edouardmenayde I had to fix backwards compatibility 2 weeks ago, when I tested the library against a live server, but I don't see why we couldn't merge it now and make a new release. Shouldn't be much longer, thanks for being so patient.

What you can do is give feedback of course if you encounter a problem or notice a missing feature :+1: and of course if you feel it is taking too long to get a new release, ask about the release as you did! I personally appreciate knowing that at least one person is waiting for my work to be released :sweat_smile:

**Comment by edouardmenayde** [comment]
Thanks to the merge, I was able to use the new version without any problem 🙏 

I still see some warnings from the dep when compiling the project, which will surely raise some eyebrows in my team when I will integrate the dep in our project. Are you open to working together to fix those warnings ? I can find some time to create some PRs fixing some of them.

**Comment by Ninigi** [comment]
PRs to get rid of warnings would be very appreciated!

**Pull request merged**
